# SPDX-License-Identifier: GPL-2.0
# AGATE(5.10): the 5.10 import left this file EMPTY and mediatek/Makefile never
# descended into base/ at all; 4.19 has `obj-y += power/` here.  Only the PPM
# dummy object is wired below for now -- clkbuf_v1/, pbm_v4/ and mdpm_v2/ are
# still unported and stay out of the build (documented gap).
obj-y += power/
