# SPDX-License-Identifier: GPL-2.0
# AGATE(5.10): created -- matches the wildcard object list that
# power/Makefile compiles flags for (each platform .c defines its
# <soc>_plat_data and the <soc>_pwr_func helpers).
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += mt6983_aputop.o mt6983_pwr_func.o
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += mt6879_aputop.o mt6879_pwr_func.o
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += mt6895_aputop.o mt6895_pwr_func.o
