# SPDX-License-Identifier: GPL-2.0
# AGATE(5.10): created -- see ../../Makefile.  Without this the objects below
# were compiled by nothing and never reached any built-in.a.
obj-y += common/
obj-y += devices/
obj-y += governor/
