# SPDX-License-Identifier: GPL-2.0
# AGATE(5.10): created to match the object list in ../../Makefile.
obj-y += dev-cb.o dev-freq-conn.o dev-freq-core.o dev-freq-iommu.o \
	 dev-freq-mdla.o dev-freq-vpu.o
