# SPDX-License-Identifier: GPL-2.0
# AGATE(5.10): created to match the object list in ../../Makefile.
obj-y += apu-clk.o apu-common.o apu-dbg.o apu-driver.o apu-of.o \
	 apu-plat.o apu-regulator.o apu-rpc.o apu-tag.o apu-trace.o
